# Importing Libraries and Load Dataset

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
original_df = df.copy()

# Initial DataSet Shape

In [8]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 891
Columns : 12

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [14]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
488,489,0,3,"Somerton, Mr. Francis William",male,30.0,0,0,A.5. 18509,8.0500,NaN,S
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q
605,606,0,3,"Lindell, Mr. Edvard Bengtsson",male,36.0,1,0,349910,15.5500,NaN,S
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
309,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,0,0,PC 17485,56.9292,E36,C

# Data Quality Report

 ## Missing Values ##

In [20]:
null_counts = df.isnull().sum()

null_percentage = (df.isnull().sum()/len(df))*100

quality = pd.DataFrame({
    "Null Count":null_counts,
    "Null %":null_percentage.round(2)
})

quality

             Null Count  Null %
PassengerId           0    0.00
Survived              0    0.00
Pclass                0    0.00
Name                  0    0.00
Sex                   0    0.00
Age                 177   19.87
SibSp                 0    0.00
Parch                 0    0.00
Ticket                0    0.00
Fare                  0    0.00
Cabin               687   77.10
Embarked              2    0.22

## Duplicate Rows

In [23]:
duplicates = df.duplicated().sum()

print("Duplicate Rows =",duplicates)

Duplicate Rows = 0

# Data Types

In [26]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# Value Range Anomalies

In [29]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [37]:
df[df["Age"]<0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [39]:
df[df["Fare"]<0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

### Value Range Anomalies

The Age and Fare columns were checked for impossible negative values.

• No records with negative Age were found.
• No records with negative Fare were found.

Therefore, no corrections were required for these columns.

In [84]:
g=df[df["Age"] > 100]
g

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

In [82]:
c=df["Fare"].describe()
c

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [54]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [80]:
t=df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
t

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

# Dupliacte Removal

In [63]:
duplicates_before = df.duplicated().sum()

df.drop_duplicates(inplace=True)

duplicates_after = df.duplicated().sum()

print("Duplicates Removed =",duplicates_before-duplicates_after)

Duplicates Removed = 0

No Duplicates were found in dataset

# Standardisation

In [68]:
f=df["Sex"] = df["Sex"].str.strip().str.title()
f

0        Male
1      Female
2      Female
3      Female
4        Male
        ...
886      Male
887    Female
888    Female
889      Male
890      Male
Name: Sex, Length: 891, dtype: object

In [88]:
g=df["Embarked"] = df["Embarked"].str.upper()
g

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [90]:
r=df["Name"] = df["Name"].str.strip()
r

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

# Data Type Conversion

Passender id
Age
Fare

In [96]:
p=df["PassengerId"] = df["PassengerId"].astype(str)
p

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: object

In [100]:
a=df["Age"] = df["Age"].astype(int)
a

0      22
1      38
2      26
3      35
4      35
       ..
886    27
887    19
888    28
889    26
890    32
Name: Age, Length: 891, dtype: int32

In [106]:
f=df["Fare"] = df["Fare"].astype(float,3)
f

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

# Outlier Detection (IQR Method)

In [109]:
Q1 = df["Age"].quantile(0.25)

Q3 = df["Age"].quantile(0.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR

upper = Q3+1.5*IQR

outliers_age = df[(df["Age"]<lower)|(df["Age"]>upper)]

print("Age Outliers =",len(outliers_age))

Age Outliers = 66

Age: 66 outliers were detected using the IQR method. These values represent genuine passenger ages and were retained because they are valid observations rather than data-entry errors.

In [111]:
Q1 = df["Fare"].quantile(0.25)

Q3 = df["Fare"].quantile(0.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR

upper = Q3+1.5*IQR

outliers_fare = df[(df["Fare"]<lower)|(df["Fare"]>upper)]

print("Fare Outliers =",len(outliers_fare))

Fare Outliers = 116

Fare: 116 outliers were detected. Extremely high fares were capped at the upper IQR boundary using the IQR method to reduce the influence of extreme values while preserving all observations.

In [127]:

df["Fare"] = np.where(df["Fare"] > upper, upper, df["Fare"])

df["Fare"] = np.where(df["Fare"] < lower, lower, df["Fare"])

In [129]:
outliers_after = df[(df["Fare"] < lower) | (df["Fare"] > upper)]

print("Fare Outliers After:", len(outliers_after))

Fare Outliers After: 0

# utlier Decision
Age outliers were retained because extremely young and elderly passengers are valid observations.
Fare outliers were capped using the IQR upper bound to reduce the influence of extremely high ticket prices while preserving all records.

# Final quality check

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    object
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int32
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(1), int32(1), int64(4), object(5)
memory usage: 73.2+ KB

In [135]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [137]:
df.duplicated().sum()

0

# Before and After Summary

In [140]:
summary = pd.DataFrame({
    "Metric":[
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows",
        "Data Types Correct"
    ],
    "Before":[
        original_df.shape[0],
        original_df.shape[1],
        original_df.isnull().sum().sum(),
        original_df.duplicated().sum(),
        "No"
    ],
    "After":[
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        "Yes"
    ]
})

summary

               Metric Before After
0                Rows    891   891
1             Columns     12    11
2      Missing Values    866     0
3      Duplicate Rows      0     0
4  Data Types Correct     No   Yes

In [142]:
df.to_csv("Titanic_Cleaned.csv",index=False)

In [144]:
df1=pd.read_csv("Titanic_Cleaned.csv")
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38,1,0,PC 17599,65.6344,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",Male,35,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,28,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",Male,26,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",Male,32,0,0,370376,7.7500,Q

# Project Conclusion

## Conclusion

The Titanic dataset was successfully cleaned using pandas and NumPy.

The following data cleaning operations were performed:

- Generated a data quality report.
- Handled missing values using median and mode imputation.
- Removed the Cabin column due to excessive missing values.
- Verified and removed duplicate records where applicable.
- Standardized categorical values.
- Corrected data types.
- Detected outliers using the IQR method.
- Retained valid Age outliers and capped Fare outliers.
- Produced a before-versus-after summary.
- Exported the cleaned dataset as `Titanic_Cleaned.csv`.

The resulting dataset is complete, consistent, and ready for exploratory data analysis and machine learning.